### PR TITLE
Fix Home Screen layout broken on large fonts

### PR DESCRIPTION
**Pull request by piyush23dez**
https://github.com/zcash/zcash-ios-wallet/issues/252

### CODE REVIEW

**Comment by pacu** [comment]
Thanks for the contribution @piyush23dez 
Is there a way that you could detach formatting changes from the specific changes that belong to the fix?

**Review by pacu — CHANGES_REQUESTED** [review]
Thanks for the contribution @piyush23dez
Is there a way that you could detach formatting changes from the specific changes that belong to the fix?

**Comment by piyush23dez** [comment]
Hey @pacu, Code changes are done in PR need to be formatted otherwise the code looks messy, and without formatting code changes will look copy-paste, and there will be no indentation for each block of closure. So I think we should follow these style guides with new changes with proper code formatted in future. please review the changes.

**Comment by pacu** [comment]
@piyush23dez I appreciate you've worried about code formatting. What I'm asking is to make those changes on a separate commit so that any formatting source code changes are not mixed up with the changes that actually perform the fix of the issue.

this two benefits:

- PRs are more concise and comprehensive, therefore easier to review.
- in case of regressions your formatting changes won't be reverted

**Comment by piyush23dez** [comment]
> @piyush23dez I appreciate you've worried about code formatting. What I'm asking is to make those changes on a separate commit so that any formatting source code changes are not mixed up with the changes that actually perform the fix of the issue.
> 
> this two benefits:
> 
> * PRs are more concise and comprehensive, therefore easier to review.
> * in case of regressions your formatting changes won't be reverted

@pacu  so as of now most of the changes to fix the layout are being done that has to be around the existing code, so for example if you have a block and you want to nest inside another block we can't write code just on the same line, it has to be indented. otherwise how we can separate the code and it's formatting in different PRs, i agree with you that code formatting for different sections of the code can be done separately, i can revert the changes in other sections of. the code. but the new code changes formatting needs to be in place.

**Comment by piyush23dez** [comment]
Created new PR with clean slate https://github.com/zcash/zcash-ios-wallet/pull/264

**Pull request closed without merging**
